### ISSUE TITLE
Doesn't work!

### ISSUE THREAD

**Issue by WobbyChip** [lreiner/Whatsapp-Message-Spammer#3]
Actually, this script worked before, but now it doesn't work, I think it associated with something changed in WhatsApp, so could you please fix it.

**Comment by lreiner** [comment]
Ah sorry yeah most of the time they change their class names. 
I will update the class names soon and it will be working again.

**Comment by lreiner** [comment]
fixed with e7c6baa704d31e25d1287446e2c1f5f8429a37ae . Working again 👍
