### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by kindvy** [lreiner/Whatsapp-Message-Spammer#4]
[var allElementsClassName = "_2HS9r";]-----> update this to
[var allElementsClassName = "_2vikl";]-----> this

whatsapp got update for several week ago

**Comment by almahdiamiry** [comment]
and also change this
var input = document.getElementsByClassName(inputMessageClassName + " copyable-text selectable-text")[0];

change 0 to 1 like this

var input = document.getElementsByClassName(inputMessageClassName + " copyable-text selectable-text")[0];

**Comment by lreiner** [comment]
fixed thanks 👍
